import Footer from './Components/Footer'
import Navbar from './Components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Medical Landing Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar />
       <main className=''>
      {children}
       </main>
       <Footer /> 
        
        </body>
       
    </html>
  )
}
